# http://module-build.sourceforge.net/META-spec.html
#XXXXXXX This is a prototype!!!  It will change in the future!!! XXXXX#
name:         Apache-Pod
version:      0.03
version_from: lib/Apache/Pod.pm
installdirs:  site
requires:
    File::Find:                    0
    File::Spec:                    0
    Pod::Find:                     0
    Pod::Simple:                   0.93
    Pod::Simple::HTML:             0
    Pod::Simple::Text:             0
    Test::More:                    0

distribution_type: module
generated_by: ExtUtils::MakeMaker version 6.16
